### ISSUE TITLE
20200521 User Test with Polina

### ISSUE THREAD

**Issue by invisibleroads** [AmericanPublicPowerAssociation/asset-tracker-client#220]
# Map Highlighting
- [ ] Fix why red selection is not aligning with details window
- [ ] Keep red selection after deleting line endpoint
- [x] Have different map indicators for asset details vs bus connection click (red in map for asset details and map popup for bus connection click)
- [ ] Fix wrong bus highlight
- [ ] Highlight bus in yellow if user clicks on contained asset
- [ ] Highlight asset in red if user clicks on asset in details

# Tasks and Task Comments
- [x] Fix task rename is not working
- [x] Fix task comments not saving
- [x] Fix task comments appearing everywhere

# Risks
- [x] Fix risk table not appearing properly

# Imports
- [ ] Fix import CSV

# Attributes
- [ ] Fix select fields
    - [ ] Label should go in middle
    - [ ] Fix spacing for select to be consistent with other fields

# Connectivity Edge Cases
- [ ] Delete line middle vertex if it is empty after removing line
- [x] Update connection when deleting middle vertex
- [ ] Fix why add line from bus to line is not adding the line to the bus
- [ ] Fix case when drawing a line too close to another line (it loses a head)
- [ ] Fix connectivity edge cases for dragging meter and transformer
- [ ] Have delete vertex be separate from dragging vertex
- [ ] Figure out how to stay focused on line asset after deleting line endpoint
- [ ] Update bus numbers when adding vertices to a line

# Miscellaneous
- [x] Fix bounding box for single point (it zooms out too much)
- [x] Restore confirmation dialog on pressing delete
- [ ] Let user press delete immediately after entering edit mode
- [ ] Figure out why line length is triggering uncontrolled component
- [ ] Decide what to do if task name is super long
